// Generated by https://quicktype.io

interface Lang {
	commands: { [key: string]: string };
	commandhander: Commandhander;
	chat: Chat;
	playerstatuses: Playerstatuses;
	kickmessages: { [key: string]: string };
	errors: { [key: string]: string };
	server: Server;
	devdebug: Devdebug;
	logger: Logger;
	broadcasts: Broadcasts;
	other: Other;
}

export default Lang;

interface Broadcasts {
	joinedTheGame: string;
	leftTheGame: string;
	broadcastmessage: string;
}

interface Chat {
	chatFormat: string;
	chatMessage: string;
}

interface Commandhander {
	cchs: string;
	scch: string;
}

interface Devdebug {
	ignoredPacket: string;
	debug: string;
	unhandledPacket: string;
	unhandledPacketData: string;
	unstableWarning: string;
}

interface Logger {
	info: string;
	warning: string;
	error: string;
	debug: string;
}

interface Other {
	unknown: string;
	server: string;
}

interface Playerstatuses {
	joined: string;
	rpsInstalled: string;
	rpsRefused: string;
	disconnected: string;
	spawned: string;
	norpsInstalled: string;
	playerConnected: string;
}

interface Server {
	listeningOn: string;
	loadingPlugins: string;
	loadingServer: string;
	unloadingPlugin: string;
	unloadedPlugin: string;
	stoppingServer: string;
	loadingPlugin: string;
	loadedPlugin: string;
}
