network:
    host: "0.0.0.0"
    port: 19132
    raknet: "raknet-native" # Can be raknet-native, jsp-raknet or raknet-node 
    packet_rate_limiting: # Limits how many packets can be sent per second
        enabled: true # Recommended to enable. It can prevent bad actors from crashing your server
        max_packets: 2500
server_info:
    motd: "§aGreenFrog server"
    level_name: "GreenFrog"
    version: "1.20.50"
    offline_mode: false
    max_players: 10
chat:
    lang: "en_US" # Can be "en_US", "ca_ES", "es_ES", "ru_RU", "uk_UA" or "vi_VN"
    system_messages:
        join: false # Should messages like "X joined the game" be disabled?
        leave: false # Should messages like "X left the game" be disabled?
    features:
        chat: false # Should chat be disabled?
        commands: false # Should commands be disabled? This will won't affect console commands
    block_invalid_packets:
        messages: true # Prevents players from using invalid characters or messages with invalid length
        commands: true # Same as "messages" but for commands
query: # Query is a UDP protocol for querying server properties. More info at https://wiki.vg/Query
    enabled: true
    port: 19133
    show_plugins: false # Will querying the server show all the plugins that the server has installed?
    log:
        packets: true
        connections: false
dev:
    unstable: false # Makes your server not crash on critical errors
    debug: false
    log_unhandled_packets: false
    default_permission_level: 2 # Can be 4 (for operator), 2 (for member) or 0 (for visitor)
    multi_protocol: false # Supports versions that have no or nearly any protocol changes. Some features may be broken
    validate_usernames: true # Don't allow allow usernames that are too long/too short or duplicate usernames?
    legacy:
        use_legacy_version_mismatch_kick_message: false # Instead of `Could not connect: Outdated client!` or `Could not connect: Outdated server!` it'll say the value of `kickMessages.versionMismatch` in your lang file
        use_legacy_server_full_kick_message: false # Instead of `Wow this server is popular! Check back later to see if space opens up.` it'll say the value of `kickMessages.serverFull` in your lang file
    exit_codes:
        successful: 0
        crash: -1
world:
    name: "GreenFrog server"
    difficulty: 0 # Can be 0 (for peaceful), 1 (for easy), 2 (for normal) or 3 (for hard)
    gamemode:
        player: "creative"
        world: "creative"
    generators:
        type: "default" # The world type. Can be "default" (for a normal world), "flat" (for a superflat world), or "void" (for an empty world)
    render_distance:
        server_side: 4
        client_side: 64
    ticking:
        event: true # Should ServerTickEvent be enabled?
        time: true # Should time update be server side?
        void: true # Should people that are in void take damage?
        regeneration: true # Should people in survival mode regenerate their health?
        starvation_damage: true # Should people take starvation damage?
        entities: true # Should the server tick entity spawning?
        speed: 1000 # The tick speed
logger:
    message_format: "%date% %type% | %message%"
    dateFormat: "DD/MM/YYYY hh:mm:ss A"