network:
  host: "0.0.0.0"
  port: 19132
serverInfo:
  motd: "§aGreenFrog server"
  levelName: "GreenFrog"
  version: "1.19.80"
  offlineMode: true
  maxPlayers: 20
chat:
  lang: "en_US"
  disable: false
  commandsDisabled: false
  blockInvalidMessages: true # Prevents players from using colors in chat or spam the chat with messages that are longer than 256 chars
  blockInvalidCommands: true # Same as 'blockInvalidMessages' but for commands
dev:
  unstable: false # Makes your server not crash on critical errors
  debug: false
  crashCode: -1
  exitCode: 0
  logUnhandledPackets: false
  defaultPermissionLevel: 2
  # Permission levels are:
  # 4 - operator
  # 3 - unknown
  # 2 - member
  # 1 - unknown
  # 0 - visitor
  multiProtocol: false # Supports 1.19.<any sub versions or your version>. Some features may be broken
  useLegacyVersionMismatchKickMessage: false # Instead of `Could not connect: Outdated client!` or `Could not connect: Outdated server!` it will say the value of `kickMessages.versionMismatch` in your lang file
  useLegacyServerFullKickMessage: false # Instead of `Wow this server is popular! Check back later to see if space opens up.`  it will say the value of `kickMessages.serverFull` in your lang file
world:
  gamemode: "creative"
  worldGamemode: "creative"
  difficulty: 0

  generator: "default" # Can be default, flat, or void
  renderDistance: 4
  clientSideRenderDistance: 64

  tickEvent: true # Should ServerTickEvent be enabled?
  tickWorldTime: true # Should time update be server side?
  tickVoid: true # Should people that are in void take damage?
  tickRegeneration: true # Should people in survival mode regenerate their health?
  tickStarvationDamage: true # Should people take damage if their food level is 0?
  randomTickSpeed: 1000

  worldName: "GreenFrog server"
performance:
  garbageCollectorDelay: 60000
