name: Format

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    if: "!contains(github.actor, 'realfrogbot')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Format
        run: |
          npm run format
          git pull
          git config --global user.name "realfrogbot"
          git config --global user.email "124494132+realfrogbot@users.noreply.github.com"
          git add .
          git status | grep modified
          if [ $? -eq 0 ]; then
            git commit -m "codestyle: Formatted the code"
            git push origin ${{ github.head_ref }}:${{ github.head_ref }}
          else
            echo "No changes since last run"
          fi
